# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
default_stages:
  - pre-commit
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-vcs-permalinks
      - id: check-merge-conflict
      - id: check-added-large-files
      # - id: no-commit-to-branch
      #   args: [ --branch, main ]
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.0
    hooks:
      - id: typos
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
