#!/usr/bin/env -S bash

# This script wraps pinentry to allow dynamically 
# changing which pinentry program to use. This is
# useful, for example, to automatically use the
# TTY client when using SSH. For example, in 
# .bash_profile:
# if [ "$SSH_CLIENT" ]; then
#    export PINENTRY_USER_DATA=USE_TTY
# fi
# gpg-agent.conf:
# pinentry-program bin/pinentry-auto

pe=pinentry

case "$PINENTRY_USER_DATA" in
*USE_TTY*)  pe=pinentry-tty  ;;
*USE_CURSES*)   pe=pinentry-curses ;;
*USE_GTK2*) pe=pinentry-gtk-2 ;;
*USE_GNOME3*)   pe=pinentry-gnome3 ;;
*USE_X11*)  pe=pinentry-x11 ;;
*USE_QT*)   pe=pinentry-qt ;;
esac

/usr/bin/env -S $pe "$@"
